global:
  scrape_interval: 10s
  scrape_timeout: 8s

scrape_configs:
  - job_name: 'spring-mvc-benchmark'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:9404']